Added tenant id to api config
itspire/monolog-loki pull request #18
Opened 2022-12-23 16:16 UTC by korridor

2022-12-23 16:51 UTC, rrajkomar commented
Thank you for your contribution.  
This is indeed useful when using multi-tenancy however your PR is missing a corresponding test case.  
Please add the test case so it can be merged.

2022-12-23 16:52 UTC, rrajkomar requested changes

2022-12-23 16:52 UTC, rrajkomar commented on src/main/php/Handler/LokiHandler.php
> +            if ($this->tenantId !== null) {
```suggestion
            if (null !== $this->tenantId) {
```

2022-12-23 23:12 UTC, korridor commented
Just added a test case.

2022-12-29 17:49 UTC, rrajkomar approved these changes

2022-12-29 17:49 UTC, merged