Added needed configuration for laravel
itspire/monolog-loki pull request #7
Opened 2021-04-01 02:34 UTC by achetronic

On Laravel, we need to touch a config file to use the library. For that, i documented how to do it

2021-04-01 08:00 UTC, rrajkomar requested changes
I'm not familiar with Laravel configuration syntax so I'll rely on you for this.
Please fix remove the unnecessary line breaks as outlined here.
Other than that LGTM.

2021-04-01 08:00 UTC, rrajkomar commented on README.md
> +
```suggestion
```

2021-04-01 08:00 UTC, rrajkomar commented on README.md
> +
Please the unnecessary extra line breaks

2021-04-04 22:27 UTC, closed without merging

2021-04-04 22:28 UTC, achetronic commented
I will do a pull request without extra spaces and newlines :)